<% secrets = YAML.load_file('./secrets/secrets.yml')[ENV['RAILS_ENV'] || "development"] %>
defaults: &defaults
  cloud_crowd_server:   http://dev.sourceafrica.net:8080
  server_root:          dev.sourceafrica.net
  large_file_storage:   /mnt/large_files
  aws_region:           eu-west-1
  aws_zone:             eu-west-1c
  preconfigured_ami_id: <%= secrets['ami'] %>
  asset_root:           dev.sourceafrica.net

development:
  <<: *defaults

staging:
  <<: *defaults
  cloud_crowd_server: <%= secrets['db_host'] %>:8080
  server_root:        staging.sourceafrica.net
  asset_root:         s3.amazonaws.com/dcloud_staging

production:
  <<: *defaults
  cloud_crowd_server: <%= secrets['db_host'] %>:8080
  server_root:        sourceafrica.net
  asset_root:         s3-eu-west-1.amazonaws.com/s3.sourceafrica.net
  db_volume_id:       vol-3248332d

test:
  <<: *defaults
